### ISSUE TITLE
ShadowMOrdre-v2.0 : Missing lib_ecology_tree_jungle_03_wood.png

### ISSUE THREAD

**Issue by Tikilou** [ShadMOrdre/lib_ecology#7]
This file is missing of ShadowMOrdre-v2.0, error message and dummy color ingame with wood of jungle tree 03.

**Comment by ShadMOrdre** [comment]
There are multiple instances of missing textures.

The more appropriate answer, is that for many of the trees, either textures were not available for the given missing images, or I simply added the three necessary nodes for trees, in an effort to expand the number of tree types.

I'll work on getting the missing image nodes commented out until textures can be obtained.  This should definitely stop those annoying messages.
